source 'https://rubygems.org'

gemspec
gem 'game_master', path: '../game_master/'

group :development do
  gem 'irbtools', require: false
  gem 'bond', require: false
  gem 'rb-inotify', require: false
  gem 'pry'
  gem 'nokogiri'
end

group :development, :test do
  gem 'guard-rspec'
  gem 'fuubar'
  gem 'rspec', '~> 2.13.0'
end

