---
# :game_dir entry
# valid if directory exists
# defaults to: directory that contains the game_config.yml file
# if loading from string or io object, this must be set explicitly
#:game_dir: "/streets_of_gotham"

# :game_name entry
# defaults to: a capitalized, spaced version of the game_dir name
#:game_name: Streets Of Gotham

# :game_config_file entry
# defaults to: name of file the config was loaded from.  Not used if loaded from string or IO
#:game_config_file: "/streets_of_gotham/game_config.yml"

# :game_module_name entry
# valid if: module exists
# defaults to: game_name upper_camelcased
#:game_module_name: StreetsOfGotham

# :game_class_name entry
# valid if: class exists in module of :game_module_name
# defaults to Game
#:game_class_name: Game

# :game_part_files entry
# contains list of other *_parts.yml files to read
# will look for a Maker module to
# defaults to contents of game_dir/etc/*_parts.yml
#:game_part_files: [etc/board_parts.yml]
